version: '3.8'

services:
  jarvis-chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    environment:
      # Application Configuration
      - NODE_ENV=production
      - VITE_APP_ENV=${VITE_APP_ENV:-production}
      - VITE_APP_VERSION=${VITE_APP_VERSION}
      - VITE_APP_DOMAIN=${VITE_APP_DOMAIN}
      - VITE_CDN_URL=${VITE_CDN_URL}

      # Database & Authentication
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}

      # External Integrations
      - VITE_N8N_WEBHOOK_URL=${VITE_N8N_WEBHOOK_URL}
      - N8N_WEBHOOK_SECRET=${N8N_WEBHOOK_SECRET}
      - N8N_API_KEY=${N8N_API_KEY}

      # Monitoring & Logging
      - VITE_SENTRY_DSN=${VITE_SENTRY_DSN}
      - DATADOG_API_KEY=${DATADOG_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-warn}
      - ENABLE_ANALYTICS=${ENABLE_ANALYTICS:-true}

      # Performance & Security
      - ENABLE_CACHING=${ENABLE_CACHING:-true}
      - CACHE_TTL=${CACHE_TTL:-3600}
      - COMPRESSION_ENABLED=${COMPRESSION_ENABLED:-true}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-900}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-1000}
      - CSP_ENABLED=${CSP_ENABLED:-true}

      # Security Secrets (server-side only)
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}

      # Webhook Configuration
      - WEBHOOK_TIMEOUT=${WEBHOOK_TIMEOUT:-30000}
      - WEBHOOK_RETRY_ATTEMPTS=${WEBHOOK_RETRY_ATTEMPTS:-3}
      - WEBHOOK_CIRCUIT_BREAKER_THRESHOLD=${WEBHOOK_CIRCUIT_BREAKER_THRESHOLD:-5}
      - WEBHOOK_MONITORING_ENABLED=${WEBHOOK_MONITORING_ENABLED:-true}
    restart: unless-stopped
    networks:
      - jarvis-network

  # For local development with hot reload
  jarvis-chat-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    profiles:
      - dev
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      # Application Configuration
      - NODE_ENV=development
      - VITE_APP_ENV=${VITE_APP_ENV:-development}
      - VITE_APP_VERSION=${VITE_APP_VERSION:-dev}
      - VITE_APP_DOMAIN=${VITE_APP_DOMAIN:-localhost:5173}

      # Database & Authentication
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}

      # External Integrations
      - VITE_N8N_WEBHOOK_URL=${VITE_N8N_WEBHOOK_URL}
      - N8N_WEBHOOK_SECRET=${N8N_WEBHOOK_SECRET}

      # Monitoring & Logging
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - ENABLE_ANALYTICS=${ENABLE_ANALYTICS:-false}

      # Feature Flags (Development)
      - ENABLE_DEBUG_TOOLS=${ENABLE_DEBUG_TOOLS:-true}
      - ENABLE_EXPERIMENTAL_FEATURES=${ENABLE_EXPERIMENTAL_FEATURES:-true}
      - MOCK_N8N_RESPONSES=${MOCK_N8N_RESPONSES:-true}
      - BYPASS_AUTH=${BYPASS_AUTH:-false}

      # Performance & Security (Development defaults)
      - ENABLE_CACHING=${ENABLE_CACHING:-false}
      - CSP_ENABLED=${CSP_ENABLED:-false}

      # Webhook Configuration
      - WEBHOOK_TIMEOUT=${WEBHOOK_TIMEOUT:-10000}
      - WEBHOOK_RETRY_ATTEMPTS=${WEBHOOK_RETRY_ATTEMPTS:-1}
      - WEBHOOK_MONITORING_ENABLED=${WEBHOOK_MONITORING_ENABLED:-true}
    networks:
      - jarvis-network

networks:
  jarvis-network:
    driver: bridge